<!DOCTYPE html>
<html>
	<head>
		<title>高级技巧</title>
		<?php
			include('../header.php');
		?>
	</head>
	<body>
		<div class="reveal">
			<div class="slides">
				<section>
					<section>
						<h1>高级技巧</h1>
					</section>
					<section>
                        <p></p>
					</section>
				</section>
				<section>
					<section>
						<h2>高级函数</h2>
					</section>
					<section>
                        <h3></h3>
                        <p></p>
					</section>
					<section>
                        <h3></h3>
                        <p></p>
					</section>
					<section>
                        <h3></h3>
                        <p></p>
					</section>
					<section>
                        <h3></h3>
                        <p></p>
					</section>
					<section>
                        <h3></h3>
                        <p></p>
					</section>
				</section>
				<section>
					<section>
						<h2>防篡改对象</h2>
					</section>
					<section>
                        <h3></h3>
                        <p></p>
					</section>
					<section>
                        <h3></h3>
                        <p></p>
					</section>
					<section>
                        <h3></h3>
                        <p></p>
					</section>
				</section>
				<section>
					<section>
						<h2>高级定时器</h2>
					</section>
					<section>
                        <h3></h3>
                        <p></p>
					</section>
					<section>
                        <h3></h3>
                        <p></p>
					</section>
					<section>
                        <h3></h3>
                        <p></p>
					</section>
				</section>
				<section>
					<section>
						<h2>自定义事件</h2>
					</section>
				</section>
				<section>
					<section>
						<h2>拖放</h2>
					</section>
					<section>
                        <h3></h3>
                        <p></p>
					</section>
					<section>
                        <h3></h3>
                        <p></p>
					</section>
				</section>
				<section>
					<section>
						<h2>小结</h2>
					</section>
				</section>
			</div>
		</div>
		<?php
			include('../footer.php');
		?>
	</body>
</html>
