<!DOCTYPE html>
<html>
<head lang="zh-cn">
    <title>DOM2和DOM3</title>
    <?php
        include('../header.php');
    ?>
</head>
<body>
    <div class="reveal">
        <div class="slides">
            <section>
                <section>
                    <h1>DOM2和DOM3</h1>
                </section>
                <section>
                    <p><p>
                </section>
            </section>
            <section>
                <section>
                    <h2>DOM变化</h2>
                </section>
                <section>
                    <h3>针对XML命名空间的变化</h3>
                    <p><p>
                </section>
                <section>
                    <h3>其它方面的变化</h3>
                    <p><p>
                </section>
            </section>
            <section>
                <section>
                    <h2>样式</h2>
                </section>
                <section>
                    <h3>访问元素的样式</h3>
                    <p><p>
                </section>
                <section>
                    <h3>操作样式表</h3>
                    <p><p>
                </section>
                <section>
                    <h3>元素大小</h3>
                    <p><p>
                </section>
                <section>
                    <p><p>
                </section>
            </section>
            <section>
                <section>
                    <h2>遍历</h2>
                </section>
                <section>
                    <h3>NodeIterator</h3>
                    <p><p>
                </section>
                <section>
                    <h3>TreeWalker</h3>
                    <p><p>
                </section>
                <section>
                    <p><p>
                </section>
            </section>
            <section>
                <section>
                    <h2>范围</h2>
                </section>
                <section>
                    <h3>DOM中的范围</h3>
                    <p><p>
                </section>
                <section>
                    <h3>IE中的范围</h3>
                    <p><p>
                </section>
                <section>
                    <p><p>
                </section>
            </section>
            <section>
                <section>
                    <h2>小结</h2>
                </section>
                <section>
                    <p><p>
                </section>
            </section>
        </div>
    </div>
    <?php
        include('../footer.php');
    ?>
</body>
</html>
