<!DOCTYPE html>
<html>
<head lang="zh-cn">
    <title>DOM扩展</title>
    <?php
        include('../header.php');
    ?>
</head>
<body>
    <div class="reveal">
        <div class="slides">
            <section>
                <section>
                    <h1>DOM扩展</h1>
                </section>
                <section>
                    <p><p>
                </section>
            </section>
            <section>
                <section>
                    <h2>选择符API</h2>
                </section>
                <section>
                    <h3>querySelector方法</h3>
                    <p><p>
                </section>
                <section>
                    <h3>querySelectorAll方法</h3>
                    <p><p>
                </section>
                <section>
                    <h3>matchesSelector方法</h3>
                    <p><p>
                </section>
            </section>
            <section>
                <section>
                    <h2>元素遍历</h2>
                </section>
                <section>
                    <p><p>
                </section>
            </section>
            <section>
                <section>
                    <h2>HTML5</h2>
                </section>
                <section>
                    <h3>与类相关的扩充</h3>
                    <p><p>
                </section>
                <section>
                    <h3>焦点管理</h3>
                    <p><p>
                </section>
                <section>
                    <h3>HTMLDocument的变化</h3>
                    <p><p>
                </section>
                <section>
                    <h3>字符集属性</h3>
                    <p><p>
                </section>
                <section>
                    <h3>自定义数据属性</h3>
                    <p><p>
                </section>
                <section>
                    <h3>插入标记</h3>
                    <p><p>
                </section>
                <section>
                    <h3>scrollIntoView方法</h3>
                    <p><p>
                </section>
            </section>
            <section>
                <section>
                    <h2>专有扩展</h2>
                </section>
                <section>
                    <h3>文档模式</h3>
                    <p><p>
                </section>
                <section>
                    <h3>children属性</h3>
                    <p><p>
                </section>
                <section>
                    <h3>contains方法</h3>
                    <p><p>
                </section>
                <section>
                    <h3>插入文本</h3>
                    <p><p>
                </section>
                <section>
                    <h3>滚动</h3>
                    <p><p>
                </section>
            </section>
            <section>
                <section>
                    <h2>小结</h2>
                </section>
                <section>
                    <p><p>
                </section>
            </section>
        </div>
    </div>
    <?php
        include('../footer.php');
    ?>
</body>
</html>
