<!DOCTYPE html>
<html>
	<head>
		<title>新兴的API</title>
		<?php
			include('../header.php');
		?>
	</head>
	<body>
		<div class="reveal">
			<div class="slides">
				<section>
					<section>
						<h1>新兴的API</h1>
					</section>
					<section>
					</section>
				</section>
				<section>
					<section>
						<h2>requestAnimationFrame</h2>
					</section>
					<section>
                        <h3>早期动画循环</h3>
                        <p></p>
					</section>
					<section>
                        <h3>循环间隔的问题</h3>
                        <p></p>
					</section>
					<section>
                        <h3>mozRequestAnimationFrame</h3>
                        <p></p>
					</section>
					<section>
                        <h3>webkitRequestAnimationFrame与msRequestAnimationFrame</h3>
                        <p></p>
					</section>
				</section>
				<section>
					<section>
						<h2>Page Visibility API</h2>
					</section>
				</section>
				<section>
					<section>
						<h2>Geolocation API</h2>
					</section>
				</section>
				<section>
					<section>
						<h2>File API</h2>
					</section>
					<section>
                        <h3>FileReader类型</h3>
                        <p></p>
					</section>
					<section>
                        <h3>读取部分内容</h3>
                        <p></p>
					</section>
					<section>
                        <h3>对象URL</h3>
                        <p></p>
					</section>
					<section>
                        <h3>读取拖放的文件</h3>
                        <p></p>
					</section>
					<section>
                        <h3>使用XHR上传文件</h3>
                        <p></p>
					</section>
				</section>
				<section>
					<section>
						<h2>Web计时</h2>
					</section>
				</section>
				<section>
					<section>
						<h2>Web Worker</h2>
					</section>
					<section>
                        <h3>使用Worker</h3>
                        <p></p>
					</section>
					<section>
                        <h3>Worker全局作用域</h3>
                        <p></p>
					</section>
					<section>
                        <h3>包含其他脚本</h3>
                        <p></p>
					</section>
					<section>
                        <h3>Web Worker的未来</h3>
                        <p></p>
					</section>
				</section>
				<section>
					<section>
						<h2>小结</h2>
					</section>
					<section>
                        <p></p>
					</section>
				</section>
			</div>
		</div>
		<?php
			include('../footer.php');
		?>
	</body>
</html>
